controller_node:
    ros__parameters:
        velocity_max: 0.5
        acceleration_max : 0.5
        Kp:
            Kp_joint_1: 5.0
            Kp_joint_2: 10.0
            Kp_joint_3: 10.0
        Ki:
            Ki_joint_1: 0.3
            Ki_joint_2: 0.3
            Ki_joint_3: 0.3
        Kd:
            Kd_joint_1: 2.0
            Kd_joint_2: 2.0
            Kd_joint_3: 2.0