controller_node:
    ros__parameters:
        velocity_max: 0.5
        acceleration_max : 0.5
        Kp:
            Kp_joint_1: 1.0
            Kp_joint_2: 5.0
            Kp_joint_3: 3.0
        Ki:
            Ki_joint_1: 0.001
            Ki_joint_2: 0.002
            Ki_joint_3: 0.003
        Kd:
            Kd_joint_1: 2.0
            Kd_joint_2: 2.0
            Kd_joint_3: 2.0